[services.closetculture-backend]
path = "backend/closetculture-backend"
dockerfilePath = "Dockerfile"
buildContext = "."
runCommand = "java -jar target/ClosetCulture-0.0.1-SNAPSHOT.jar"
port = 8080

[services.closetculture-backend.env]
MYSQL_HOST = "${MYSQLHOST}"
MYSQL_PORT = "56538"
MYSQL_USER = "${MYSQLUSER}"
MYSQL_PASSWORD = "${MYSQL_ROOT_PASSWORD}"
MYSQL_DATABASE = "${MYSQL_DATABASE}"
